import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Bold,
  BookOpen,
  Calendar,
  ChartColumn,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CloudOff,
  CloudUpload,
  Code2,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  GripVertical,
  HardDrive,
  House,
  Image,
  Inbox,
  Info,
  Italic,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Link2,
  List,
  ListFilter,
  ListTodo,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  Menu,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  Pipette,
  Plus,
  Receipt,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Settings,
  ShoppingCart,
  Smartphone,
  Sun,
  Tablet,
  Trash2,
  Truck,
  Underline,
  UserRound,
  Users,
  Wallet,
  X,
  XCircle,
} from "lucide-react";

/**
 * Named kit glyphs: `<Icon name="…" />` renders one of these. Components and examples take glyphs
 * from here instead of importing `lucide-react` or drawing their own `<svg>`; a domain glyph the
 * kit lacks goes through `createIcon`.
 */
export const iconRegistry = {
  "nav.chevronDown": ChevronDown,
  "nav.chevronLeft": ChevronLeft,
  "nav.chevronRight": ChevronRight,
  "nav.chevronUp": ChevronUp,
  "nav.chevronsLeft": ChevronsLeft,
  "nav.chevronsUpDown": ChevronsUpDown,
  "nav.dashboard": LayoutDashboard,
  "nav.home": House,
  "nav.itemDot": Circle,
  "nav.layoutGrid": LayoutGrid,
  "nav.menu": Menu,
  "nav.sidebarCollapse": PanelLeftClose,
  "nav.sidebarExpand": PanelLeftOpen,
  "action.add": Plus,
  "action.check": Check,
  "action.close": X,
  "action.copy": Copy,
  "action.delete": Trash2,
  "action.download": Download,
  "action.drag": GripVertical,
  "action.externalLink": ExternalLink,
  "action.eyedropper": Pipette,
  "action.filter": ListFilter,
  "action.login": LogIn,
  "action.logout": LogOut,
  "action.more": MoreHorizontal,
  "action.refresh": RefreshCw,
  "action.remove": Minus,
  "action.search": Search,
  "action.send": Send,
  "action.settings": Settings,
  "action.upload": CloudUpload,
  "field.calendar": Calendar,
  "field.email": Mail,
  "field.password.show": Eye,
  "field.password.hide": EyeOff,
  "format.bold": Bold,
  "format.italic": Italic,
  "format.link": Link2,
  "format.list": List,
  "format.underline": Underline,
  "object.activity": Activity,
  "object.bell": Bell,
  "object.book": BookOpen,
  "object.cart": ShoppingCart,
  "object.chart": ChartColumn,
  "object.document": FileText,
  "object.image": Image,
  "object.inbox": Inbox,
  "object.key": KeyRound,
  "object.message": MessageSquare,
  "object.package": Package,
  "object.receipt": Receipt,
  "object.rocket": Rocket,
  "object.storage": HardDrive,
  "object.tasks": ListTodo,
  "object.truck": Truck,
  "object.user": UserRound,
  "object.users": Users,
  "object.wallet": Wallet,
  "sort.ascending": ArrowUp,
  "sort.descending": ArrowDown,
  "sort.none": ArrowUpDown,
  "status.danger": XCircle,
  "status.emailSent": MailCheck,
  "status.info": Info,
  "status.locked": Lock,
  "status.offline": CloudOff,
  "status.success": CheckCircle2,
  "status.warning": AlertTriangle,
  "theme.dark": Moon,
  "theme.light": Sun,
  "view.code": Code2,
  "view.preview": Eye,
  "viewport.desktop": Monitor,
  "viewport.mobile": Smartphone,
  "viewport.tablet": Tablet,
} as const;

export type IconName = keyof typeof iconRegistry;
