import type { ComponentApi } from "../../../scripts/docs/componentApi";

export const api: ComponentApi = {
  parts: [
    {
      name: "TagSelect",
      en: 'No ref. The field frame with a chip row and an `<input role="combobox">`, and a portaled multi-select list; options come as data.',
      ru: 'Поле с чипами и полем ввода `role="combobox"` и выпадающий список с несколькими значениями; опции — данные.',
      props: [
        {
          name: "options",
          type: "TagSelectOption[]",
          required: true,
          en: "Available tags: `{ value, label, color?, disabled? }`.",
          ru: "Доступные теги: `{ value, label, color?, disabled? }`.",
        },
        {
          name: "value",
          type: "string[]",
          en: "Controlled picked values.",
          ru: "Управляемые выбранные значения.",
        },
        {
          name: "defaultValue",
          type: "string[]",
          default: "[]",
          en: "Initial picked values, uncontrolled.",
          ru: "Начальные значения без контроля.",
        },
        {
          name: "onValueChange",
          type: "(value: string[]) => void",
          en: "Called with the new list after a pick, a removal or a creation.",
          ru: "Вызывается с новым списком после выбора, удаления или создания.",
        },
        {
          name: "open · defaultOpen · onOpenChange",
          type: "boolean · boolean · (open: boolean) => void",
          en: "Open state of the list: controlled, initial (default `false`), and the callback on every open and close.",
          ru: "Открытие списка: управляемое, начальное (по умолчанию `false`) и колбэк на каждое открытие и закрытие.",
        },
        {
          name: "creatable",
          type: "boolean",
          default: "false",
          en: "A typed text that is not an option can be added (the Create row or Enter).",
          ru: "Набранный текст, которого нет в опциях, можно добавить (строка «Создать» или Enter).",
        },
        {
          name: "onCreate",
          type: "(value: string) => void",
          en: "A new value was created, not picked from `options`.",
          ru: "Создано новое значение, а не выбрано из `options`.",
        },
        {
          name: "defaultColor",
          type: "PaletteColor",
          default: '"gray"',
          en: "Chip color of values without an option color, created ones included.",
          ru: "Цвет чипа без цвета опции, в том числе у созданных.",
        },
        {
          name: "onOptionUpdate",
          type: "(value: string, updates: { label?: string; color?: PaletteColor }) => void",
          en: "Enables the row «⋯» menu with the tag name and color; `value` never changes.",
          ru: "Включает меню «⋯» у строки: имя и цвет тега; `value` не меняется.",
        },
        {
          name: "onOptionDelete",
          type: "(value: string) => void",
          en: "Enables «Удалить» in the row menu; the value also leaves the selection.",
          ru: "Включает «Удалить» в меню строки; значение уходит и из выбранных.",
        },
        {
          name: "label",
          type: "ReactNode",
          en: "Field label above; names the input.",
          ru: "Подпись над полем; даёт имя полю ввода.",
        },
        {
          name: "hint",
          type: "ReactNode",
          en: "Support text under the field; linked by `aria-describedby`.",
          ru: "Подсказка под полем; связана через `aria-describedby`.",
        },
        {
          name: "error",
          type: "ReactNode",
          en: "Error message; replaces the hint and implies `invalid`.",
          ru: "Ошибка; заменяет подсказку и включает `invalid`.",
        },
        {
          name: "required",
          type: "boolean",
          default: "false",
          en: "Red `*` after the label and `aria-required` on the input.",
          ru: "Красная `*` после подписи и `aria-required` на поле.",
        },
        {
          name: "optional",
          type: "boolean",
          en: "Muted `labels.optional` after the label.",
          ru: "Приглушённое `labels.optional` после подписи.",
        },
        {
          name: "invalid",
          type: "boolean",
          default: "false",
          en: "Danger inset ring and `aria-invalid`.",
          ru: "Красное внутреннее кольцо и `aria-invalid`.",
        },
        {
          name: "disabled",
          type: "boolean",
          default: "false",
          en: "Disabled field and chips; the list never opens.",
          ru: "Неактивное поле и чипы; список не открывается.",
        },
        {
          name: "placeholder",
          type: "string",
          default: '""',
          en: "Text in the input while no tag is picked.",
          ru: "Текст в поле, пока нет тегов.",
        },
        {
          name: "size",
          type: '"xs" | "s" | "m" | "l" | "xl"',
          default: '"m"',
          en: "Field tier; the list uses the same tier, chips one tier down.",
          ru: "Ярус поля; список того же яруса, чипы на ярус меньше.",
        },
        {
          name: "focusRing",
          type: "boolean",
          default: "true",
          en: '`false` hides the visual focus ring (`data-focus-ring="false"`), never focus or the error ring.',
          ru: "`false` скрывает кольцо фокуса, но не фокус и не кольцо ошибки.",
        },
        {
          name: "id",
          type: "string",
          en: "Id of the input; generated when omitted.",
          ru: "Id поля ввода; без него генерируется.",
        },
        {
          name: "labels",
          type: "Partial<TagSelectLabels>",
          en: "Built-in strings, see Labels (`colorNames` merges by key).",
          ru: "Системные строки, см. «Доступность» (`colorNames` сливаются по ключам).",
        },
        {
          name: "aria-label · aria-labelledby",
          type: "string",
          en: "Name of the input and the list when there is no `label`.",
          ru: "Имя поля и списка, если нет `label`.",
        },
        {
          name: "className",
          type: "string",
          en: "Class on the field frame.",
          ru: "Класс обёртки поля.",
        },
      ],
    },
  ],
  labels: [
    {
      key: "panelHint",
      default: "Выберите вариант или создайте новый",
      en: 'Line above the list; `""` hides it.',
      ru: "Строка над списком; пустая строка скрывает её.",
    },
    {
      key: "create",
      default: "Создать",
      en: "Action text before the preview of a new tag.",
      ru: "Текст действия перед превью нового тега.",
    },
    {
      key: "remove",
      default: "Удалить {label}",
      en: "Accessible name of a chip's remove button; `{label}` is the tag text.",
      ru: "Имя кнопки удаления чипа; `{label}` — текст тега.",
    },
    {
      key: "more",
      default: "Показать ещё {count}",
      en: "Accessible name of the «+N» chip; `{count}` is the number of hidden tags.",
      ru: "Имя чипа «+N»; `{count}` — число скрытых тегов.",
    },
    {
      key: "removed",
      default: "Удалено: {label}",
      en: "Screen-reader announcement after a tag is removed.",
      ru: "Объявление для скринридера после удаления тега.",
    },
    {
      key: "edit",
      default: "Изменить тег {label}",
      en: "Accessible name of a row's «⋯» menu button.",
      ru: "Имя кнопки меню «⋯» у строки.",
    },
    {
      key: "name",
      default: "Название тега",
      en: "Accessible name of the tag name field in the menu.",
      ru: "Имя поля названия тега в меню.",
    },
    {
      key: "delete",
      default: "Удалить",
      en: "Delete button in the menu.",
      ru: "Кнопка удаления в меню.",
    },
    {
      key: "colors",
      default: "Цвета",
      en: "Heading of the color list in the menu.",
      ru: "Заголовок списка цветов в меню.",
    },
    {
      key: "colorNames",
      default: "По умолчанию · Красный · Оранжевый · …",
      en: "Names of the palette colors in the menu, by `PaletteColor` key.",
      ru: "Названия цветов палитры в меню, по ключам `PaletteColor`.",
    },
    {
      key: "optional",
      default: "необязательно",
      en: "Muted marker after the label when `optional`.",
      ru: "Приглушённая пометка после подписи при `optional`.",
    },
  ],
};
