import type { ComponentApi } from "../../../scripts/docs/componentApi";

export const api: ComponentApi = {
  parts: [
    {
      name: "Dnd.Root",
      en: "No ref, no DOM of its own besides the portalled overlay and a visually hidden live region. Owns the one drag session the app shares — mount it once above every screen that drags. Without a root the parts render but do not drag.",
      ru: "Без собственной разметки, кроме оверлея в портале и скрытой live-области. Владеет единственной сессией перетаскивания — монтируйте один раз над всеми экранами. Без корня части рендерятся, но не перетаскиваются.",
      props: [
        {
          name: "labels",
          type: "Partial<DndLabels>",
          en: "Built-in strings, see Labels.",
          ru: "Системные строки, см. «Доступность».",
        },
        {
          name: "children",
          type: "ReactNode",
          en: "The app or the screen that drags.",
          ru: "Приложение или экран с перетаскиванием.",
        },
      ],
    },
    {
      name: "Dnd.Sortable",
      en: "Generic `Dnd.Sortable<T>`; `ref` → `HTMLElement`. Renders `<div>`, `<ul>` or `<ol>` and registers itself as the drop target; draws the gap and the optimistic order. Sets `data-axis` and `data-dragging`.",
      ru: "Обобщённый `Dnd.Sortable<T>`. Рендерит `<div>`, `<ul>` или `<ol>`, сам регистрируется как цель, рисует зазор и оптимистичный порядок. Ставит `data-axis` и `data-dragging`.",
      props: [
        {
          name: "items",
          type: "readonly T[]",
          required: true,
          en: "Items in their current order.",
          ru: "Элементы в текущем порядке.",
        },
        {
          name: "getId",
          type: "(item: T) => string",
          required: true,
          en: "Stable unique id; must match `Dnd.SortableItem id`.",
          ru: "Стабильный уникальный id; совпадает с `id` у `Dnd.SortableItem`.",
        },
        {
          name: "getLabel",
          type: "(item: T) => string",
          default: "the id",
          en: "Spoken by the live region.",
          ru: "Что произносит live-область.",
        },
        {
          name: "onReorder",
          type: "(id: string, beforeId: string | null) => DndReorderResult | Promise<DndReorderResult>",
          required: true,
          en: "The item `id` lands in front of `beforeId` (`null` = last); with connected lists `id` may come from another list. Apply it with `moveBefore`; return `{ ok: false }` (or reject) to roll the drawn order back.",
          ru: "Элемент `id` встаёт перед `beforeId` (`null` — в конец); у связанных списков `id` может прийти из другого списка. Применяйте через `moveBefore`; `{ ok: false }` (или отказ промиса) откатывает порядок.",
        },
        {
          name: "renderItem",
          type: "(item: T, index: number) => ReactNode",
          required: true,
          en: "Returns a `Dnd.SortableItem`.",
          ru: "Возвращает `Dnd.SortableItem`.",
        },
        {
          name: "axis",
          type: '"x" | "y"',
          default: '"y"',
          en: "A column or a single row; wrapping grids are not supported.",
          ru: "Столбец или одна строка; сетки с переносом не поддерживаются.",
        },
        {
          name: "handle",
          type: "boolean",
          default: "false",
          en: "Only `Dnd.Handle` starts a drag; the rest of the item stays free for clicks and text selection.",
          ru: "Тянуть можно только за `Dnd.Handle`; остальная строка свободна для кликов и выделения.",
        },
        {
          name: "disabled",
          type: "boolean",
          default: "false",
          en: "No drag, no keyboard reorder.",
          ru: "Без перетаскивания и перестановки с клавиатуры.",
        },
        {
          name: "kind",
          type: "string",
          default: "unique per list",
          en: "Lists sharing a `kind` exchange items (a board).",
          ru: "Списки с общим `kind` обмениваются элементами (доска).",
        },
        {
          name: "canDrop",
          type: "(id: string) => boolean",
          en: "Refuses an item by id; the list gets `data-dnd-reject` and turns `danger` before the release.",
          ru: "Отказывает элементу по id; список получает `data-dnd-reject` и краснеет до отпускания.",
        },
        {
          name: "as",
          type: '"div" | "ul" | "ol"',
          default: '"div"',
          en: "Root element; `ul` / `ol` render items as `li`.",
          ru: "Корневой элемент; при `ul` / `ol` элементы — `li`.",
        },
        {
          name: "…rest",
          type: 'Omit<HTMLAttributes<HTMLElement>, "children">',
          en: "`className` (the list layout), `aria-label` (the name of the list) and the other attributes of the list element.",
          ru: "`className` (раскладка списка), `aria-label` (имя списка) и остальные атрибуты элемента списка.",
        },
      ],
    },
    {
      name: "Dnd.SortableItem",
      en: "`ref` → `HTMLElement`. `<li>` inside `ul` / `ol`, `<div>` otherwise; throws outside `Dnd.Sortable`. Sets `data-lifted`, `data-dnd-item`, `aria-roledescription`, `aria-keyshortcuts` and `tabIndex={0}` (not with `handle`). Presses on buttons, fields, links and `[data-dnd-ignore]` inside never start a drag.",
      ru: "`<li>` в `ul` / `ol`, иначе `<div>`; вне `Dnd.Sortable` — ошибка. Ставит `data-lifted`, `data-dnd-item`, `aria-roledescription`, `aria-keyshortcuts` и `tabIndex={0}` (без `handle`). Нажатия на кнопки, поля, ссылки и `[data-dnd-ignore]` внутри не начинают перетаскивание.",
      props: [
        {
          name: "id",
          type: "string",
          required: true,
          en: "The item id (same as `getId`).",
          ru: "Id элемента (как `getId`).",
        },
        {
          name: "disabled",
          type: "boolean",
          default: "false",
          en: "This item cannot be dragged or moved.",
          ru: "Этот элемент нельзя перетащить или сдвинуть.",
        },
        {
          name: "…rest",
          type: 'Omit<HTMLAttributes<HTMLElement>, "id">',
          en: "`className` (the row look: fill, radius, padding) and the other attributes; `onPointerDown` / `onKeyDown` run first, `preventDefault()` keeps the drag from starting.",
          ru: "`className` (вид строки: заливка, радиус, отступы) и остальные атрибуты; `onPointerDown` / `onKeyDown` срабатывают первыми, `preventDefault()` отменяет перетаскивание.",
        },
      ],
    },
    {
      name: "Dnd.Handle",
      en: "`ref` → `HTMLButtonElement`. The grip: a ghost icon-only `xs` Button with the `action.drag` icon; a press always starts the drag, Alt+arrows on it reorder its item.",
      ru: "Ручка: ghost-кнопка `xs` с иконкой `action.drag`; нажатие всегда начинает перетаскивание, Alt + стрелки двигают её элемент.",
      props: [
        {
          name: "aria-label",
          type: "string",
          default: "labels.handle",
          en: "Accessible name.",
          ru: "Доступное имя.",
        },
        {
          name: "…rest",
          type: 'Omit<ButtonHTMLAttributes<HTMLButtonElement>, "type" | "children">',
          en: "`className`, `disabled` and the other button attributes.",
          ru: "`className`, `disabled` и остальные атрибуты кнопки.",
        },
      ],
    },
    {
      name: "Dnd.Draggable",
      en: "Generic `Dnd.Draggable<TData>`; `ref` → `HTMLElement`. Renders the `as` element; stays in place at reduced opacity (`data-dragging`) while carried. Has no keyboard path of its own: offer a button or a menu for the same move.",
      ru: "Обобщённый `Dnd.Draggable<TData>`. Рендерит элемент `as`; на время переноса остаётся на месте полупрозрачным (`data-dragging`). Своего клавиатурного пути нет — дайте кнопку или меню для того же действия.",
      props: [
        {
          name: "kind",
          type: "string",
          required: true,
          en: "What it is; zones accept by kind.",
          ru: "Что это; зоны принимают по виду.",
        },
        {
          name: "id",
          type: "string",
          required: true,
          en: "Unique within its kind.",
          ru: "Уникален в своём виде.",
        },
        {
          name: "data",
          type: "TData",
          en: "Payload handed to the zone's `onDrop`.",
          ru: "Данные для `onDrop` зоны.",
        },
        {
          name: "label",
          type: "string",
          default: "the id",
          en: "Spoken by the live region.",
          ru: "Что произносит live-область.",
        },
        {
          name: "disabled",
          type: "boolean",
          default: "false",
          en: "Not draggable.",
          ru: "Нельзя перетащить.",
        },
        {
          name: "handle",
          type: "boolean",
          default: "false",
          en: "Only a `Dnd.Handle` inside starts the drag.",
          ru: "Тянуть можно только за `Dnd.Handle` внутри.",
        },
        {
          name: "as",
          type: '"div" | "li" | "span" | "article" | "section"',
          default: '"div"',
          en: "Element.",
          ru: "Элемент.",
        },
        {
          name: "onDragStart",
          type: "(item, point, origin) => void",
          en: "Fired once the press became a drag.",
          ru: "Когда нажатие стало перетаскиванием.",
        },
        {
          name: "onDragEnd",
          type: '(item, outcome: "drop" | "release" | "cancel") => void',
          en: "Always fired at the end.",
          ru: "Всегда в конце.",
        },
        {
          name: "…rest",
          type: 'Omit<HTMLAttributes<HTMLElement>, "id">',
          en: "`className` and the other attributes.",
          ru: "`className` и остальные атрибуты.",
        },
      ],
    },
    {
      name: "Dnd.DropZone",
      en: "Generic `Dnd.DropZone<TData>`; `ref` → `HTMLElement`. Renders the `as` element; state is mirrored by `data-dnd-over`, `data-dnd-reject`, `data-dnd-flash`. Where zones overlap, the innermost wins.",
      ru: "Обобщённый `Dnd.DropZone<TData>`. Рендерит элемент `as`; состояние — `data-dnd-over`, `data-dnd-reject`, `data-dnd-flash`. При наложении зон побеждает внутренняя.",
      props: [
        {
          name: "accepts",
          type: "string | readonly string[] | ((item: DragItem) => boolean)",
          required: true,
          en: "Kinds it takes, or a predicate.",
          ru: "Принимаемые виды или условие.",
        },
        {
          name: "onDrop",
          type: "(item: DragItem<TData>) => void",
          required: true,
          en: "An accepted item landed.",
          ru: "Принятый элемент брошен.",
        },
        {
          name: "canDrop",
          type: "(item: DragItem<TData>) => boolean",
          en: "Refuses an item; the zone turns `danger` before the release.",
          ru: "Отказывает элементу; зона краснеет до отпускания.",
        },
        {
          name: "onEnter · onLeave",
          type: "(item) => void · () => void",
          en: "An accepted item came over / left.",
          ru: "Принимаемый элемент вошёл / вышел.",
        },
        {
          name: "flashOnDrop",
          type: "boolean",
          default: "false",
          en: "Flashes the zone after a drop.",
          ru: "Зона вспыхивает после броска.",
        },
        {
          name: "disabled",
          type: "boolean",
          default: "false",
          en: "Not a target.",
          ru: "Не цель.",
        },
        {
          name: "as",
          type: '"div" | "section" | "li" | "ul" | "ol" | "span"',
          default: '"div"',
          en: "Element.",
          ru: "Элемент.",
        },
        {
          name: "…rest",
          type: 'Omit<HTMLAttributes<HTMLElement>, "onDrop">',
          en: "`className` (the zone's own look) and the other attributes.",
          ru: "`className` (вид зоны) и остальные атрибуты.",
        },
      ],
    },
    {
      name: "moveBefore",
      en: "`moveBefore(items, id, beforeId, getId)` returns `items` with `id` moved in front of `beforeId` (`null` = last): the body of every `onReorder`.",
      ru: "`moveBefore(items, id, beforeId, getId)` возвращает `items`, где `id` стоит перед `beforeId` (`null` — в конце): тело любого `onReorder`.",
      props: [],
    },
  ],
  labels: [
    { key: "handle", default: "Перетащить", en: "Name of `Dnd.Handle`.", ru: "Имя `Dnd.Handle`." },
    {
      key: "roleDescription",
      default: "перетаскиваемый элемент",
      en: "`aria-roledescription` of every draggable item.",
      ru: "`aria-roledescription` каждого перетаскиваемого элемента.",
    },
    {
      key: "grabbed",
      default: "{label}: взят",
      en: "Live region: picked up.",
      ru: "Live-область: взят.",
    },
    {
      key: "dropped",
      default: "{label}: перемещён",
      en: "Live region: dropped on a target.",
      ru: "Live-область: брошен на цель.",
    },
    {
      key: "returned",
      default: "{label}: возвращён на место",
      en: "Live region: released over nothing.",
      ru: "Live-область: отпущен мимо целей.",
    },
    {
      key: "cancelled",
      default: "{label}: перемещение отменено",
      en: "Live region: cancelled (Escape, interruption).",
      ru: "Live-область: отменено (Escape, прерывание).",
    },
    {
      key: "moved",
      default: "{label}: позиция {position} из {total}",
      en: "Live region: moved with the keyboard.",
      ru: "Live-область: сдвинут с клавиатуры.",
    },
  ],
};
