import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

const stylesRoot = path.resolve(process.cwd(), "src/styles");
const read = (file: string) => readFileSync(path.join(stylesRoot, file), "utf8");

describe("generated token styles", () => {
  it("are generated and expose the semantic contract", () => {
    const tokensCss = read("tokens.css");
    const light = read("theme-light.css");
    const dark = read("theme-dark.css");

    for (const css of [tokensCss, light, dark]) {
      expect(css).toContain("AUTO-GENERATED by scripts/build-tokens.ts");
    }
    for (const name of [
      "--prime-color-bg-canvas",
      "--prime-color-field-bg-surface",
      "--prime-color-focus-ring",
      "--prime-control-xs-height",
      "--prime-control-xl-height",
      "--prime-text-body-m-size",
      "--prime-space-4",
      "--prime-z-modal",
      "--prime-z-tooltip-in-drawer-in-modal",
      "--prime-color-palette-teal-soft",
    ]) {
      expect(light).toContain(`${name}:`);
    }
    expect(dark).toContain("--prime-color-bg-canvas:");
    expect(dark).toContain("--prime-shadow-overlay:");
  });

  it("has no semantic token that the kit does not use", () => {
    const srcRoot = path.resolve(process.cwd(), "src");
    const generated = new Set(["tokens.css", "theme-light.css", "theme-dark.css"]);
    const sources = (readdirSync(srcRoot, { recursive: true }) as string[])
      .filter((file) => /\.(css|tsx?)$/.test(file) && !/\.test\.tsx?$/.test(file))
      .filter((file) => !generated.has(path.basename(file)))
      .map((file) => readFileSync(path.join(srcRoot, file), "utf8"))
      .join("\n");
    const declared = new Set(
      [read("theme-light.css"), read("theme-dark.css")].flatMap((css) =>
        [...css.matchAll(/^\s+(--prime-[a-z0-9-]+):/gm)].map((m) => m[1]),
      ),
    );
    const unused = [...declared].filter(
      (name) => !new RegExp(`${name}(?![a-z0-9-])`).test(sources),
    );
    expect(unused).toEqual([]);
  });

  it("keeps every space token on the 4px grid", () => {
    const values = [...read("tokens.css").matchAll(/--prime-ref-space-\d+: ([\d.]+)rem;/g)].map(
      (m) => Number(m[1]),
    );
    expect(values.length).toBeGreaterThan(8);
    for (const rem of values) {
      expect((rem * 16) % 4).toBe(0);
    }
  });
});
