import { readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

const stylesRoot = path.resolve(process.cwd(), "src/styles");

describe("generated token styles", () => {
  it("keeps generated token files in sync", () => {
    const tokensCss = readFileSync(path.join(stylesRoot, "tokens.css"), "utf8");
    const lightThemeCss = readFileSync(path.join(stylesRoot, "theme-light.css"), "utf8");
    const darkThemeCss = readFileSync(path.join(stylesRoot, "theme-dark.css"), "utf8");

    expect(tokensCss).toContain("AUTO-GENERATED by scripts/build-tokens.ts");
    expect(lightThemeCss).toContain("AUTO-GENERATED by scripts/build-tokens.ts");
    expect(darkThemeCss).toContain("AUTO-GENERATED by scripts/build-tokens.ts");

    expect(lightThemeCss).toContain("--prime-sys-typography-family-base");
    expect(lightThemeCss).toContain("--prime-sys-elevation-zIndex-modal");
    expect(lightThemeCss).toContain("--prime-sys-elevation-zIndex-toast");
    expect(lightThemeCss).toContain("--prime-sys-color-dataTable-dividerVertical");
    expect(lightThemeCss).toContain("--prime-sys-color-badge-pink-backgroundSoft");
    expect(darkThemeCss).toContain("--prime-sys-color-badge-pink-backgroundSoft");
    expect(darkThemeCss).toContain("--prime-sys-color-badge-teal-foregroundOnSoft");
    expect(darkThemeCss).toContain("--prime-sys-elevation-shadow-buttonFocus");
  });
});
