import { readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

const stylesRoot = path.resolve(process.cwd(), "src/styles");
const read = (file: string) => readFileSync(path.join(stylesRoot, file), "utf8");

describe("generated token styles", () => {
  it("are generated and expose the semantic contract", () => {
    const tokensCss = read("tokens.css");
    const light = read("theme-light.css");
    const dark = read("theme-dark.css");

    for (const css of [tokensCss, light, dark]) {
      expect(css).toContain("AUTO-GENERATED by scripts/build-tokens.ts");
    }
    for (const name of [
      "--prime-color-bg-canvas",
      "--prime-color-field-bg-surface",
      "--prime-color-focus-ring",
      "--prime-control-xs-height",
      "--prime-control-xl-height",
      "--prime-text-body-m-size",
      "--prime-space-4",
      "--prime-z-modal",
      "--prime-z-tooltip-in-drawer-in-modal",
      "--prime-color-palette-teal-soft",
    ]) {
      expect(light).toContain(`${name}:`);
    }
    expect(dark).toContain("--prime-color-bg-canvas:");
    expect(dark).toContain("--prime-shadow-overlay:");
  });

  it("keeps every space token on the 4px grid", () => {
    const values = [...read("tokens.css").matchAll(/--prime-ref-space-\d+: ([\d.]+)rem;/g)].map(
      (m) => Number(m[1]),
    );
    expect(values.length).toBeGreaterThan(8);
    for (const rem of values) {
      expect((rem * 16) % 4).toBe(0);
    }
  });
});
