import type { ComponentApi } from "../../../scripts/docs/componentApi";

export const api: ComponentApi = {
  parts: [
    {
      name: "Select.Root",
      en: "No ref. The field frame (label row · control · support row) holding the value, the open state and the search query.",
      ru: "Поле целиком: подпись, контрол, строка поддержки; хранит значение, открытие и поиск.",
      props: [
        {
          name: "value",
          type: "string | string[]",
          en: "Controlled value; `string[]` with `multiple`.",
          ru: "Управляемое значение; `string[]` при `multiple`.",
        },
        {
          name: "defaultValue",
          type: "string | string[]",
          en: "Initial value, uncontrolled.",
          ru: "Начальное значение без контроля.",
        },
        {
          name: "onValueChange",
          type: "(value: string) => void | (value: string[]) => void",
          en: 'Called with the picked value (`""` after clearing), or the new list with `multiple`.',
          ru: 'Вызывается с выбранным значением (`""` после очистки) или новым списком при `multiple`.',
        },
        {
          name: "multiple",
          type: "boolean",
          default: "false",
          en: "Several values: checkboxes in the list, the list stays open on a pick, labels joined in the trigger.",
          ru: "Несколько значений: чекбоксы в списке, список не закрывается, подписи через запятую.",
        },
        {
          name: "open · defaultOpen · onOpenChange",
          type: "boolean · boolean · (open: boolean) => void",
          en: "Open state of the list: controlled, initial (default `false`), and the callback on every open and close.",
          ru: "Открытие списка: управляемое, начальное (по умолчанию `false`) и колбэк на каждое открытие и закрытие.",
        },
        {
          name: "label",
          type: "ReactNode",
          en: "Field label above; names the trigger.",
          ru: "Подпись над полем; даёт имя триггеру.",
        },
        {
          name: "hint",
          type: "ReactNode",
          en: "Support text under the field; linked by `aria-describedby`.",
          ru: "Подсказка под полем; связана через `aria-describedby`.",
        },
        {
          name: "error",
          type: "ReactNode",
          en: "Error message; replaces the hint and implies `invalid`.",
          ru: "Ошибка; заменяет подсказку и включает `invalid`.",
        },
        {
          name: "required",
          type: "boolean",
          default: "false",
          en: "Red `*` after the label and `aria-required` on the trigger.",
          ru: "Красная `*` после подписи и `aria-required` на триггере.",
        },
        {
          name: "optional",
          type: "boolean",
          en: "Muted `labels.optional` after the label.",
          ru: "Приглушённое `labels.optional` после подписи.",
        },
        {
          name: "invalid",
          type: "boolean",
          default: "false",
          en: "Danger inset ring and `aria-invalid`.",
          ru: "Красное внутреннее кольцо и `aria-invalid`.",
        },
        {
          name: "disabled",
          type: "boolean",
          default: "false",
          en: "Disabled field; the list never opens.",
          ru: "Неактивное поле; список не открывается.",
        },
        {
          name: "loading",
          type: "boolean",
          default: "false",
          en: "Spinner instead of the chevron, `aria-busy`, a status row in the list.",
          ru: "Спиннер вместо шеврона, `aria-busy`, строка загрузки в списке.",
        },
        {
          name: "clearable",
          type: "boolean",
          default: "false",
          en: "A clear segment before the chevron while a value is set; `Delete` / `Backspace` on the trigger clear too.",
          ru: "Сегмент очистки перед шевроном, пока есть значение; `Delete` / `Backspace` на триггере тоже очищают.",
        },
        {
          name: "placeholder",
          type: "string",
          en: "Text in the trigger while nothing is picked.",
          ru: "Текст в триггере, пока ничего не выбрано.",
        },
        {
          name: "size",
          type: '"xs" | "s" | "m" | "l" | "xl"',
          default: '"m"',
          en: "Field tier: trigger height, padding, text; the list rows, the label and the hint follow it.",
          ru: "Ярус поля: высота, отступы, текст; строки списка, подпись и подсказка следуют ему.",
        },
        {
          name: "focusRing",
          type: "boolean",
          default: "true",
          en: '`false` hides the visual focus ring (`data-focus-ring="false"`), never focus or the error ring.',
          ru: "`false` скрывает кольцо фокуса, но не фокус и не кольцо ошибки.",
        },
        {
          name: "id",
          type: "string",
          en: "Id of the trigger; generated when omitted.",
          ru: "Id триггера; без него генерируется.",
        },
        {
          name: "labels",
          type: "Partial<SelectLabels>",
          en: "Built-in strings, see Labels.",
          ru: "Системные строки, см. «Доступность».",
        },
        {
          name: "className",
          type: "string",
          en: "Class on the field frame.",
          ru: "Класс обёртки поля.",
        },
        {
          name: "children",
          type: "ReactNode",
          required: true,
          en: "Trigger and Content.",
          ru: "Trigger и Content.",
        },
      ],
    },
    {
      name: "Select.Trigger",
      en: '`ref` → `HTMLButtonElement`. `<button role="combobox">` with the value, the clear segment and the chevron (a Spinner while `loading`). + native button props.',
      ru: 'Кнопка `role="combobox"`: значение, сегмент очистки и шеврон (спиннер при загрузке).',
      props: [
        {
          name: "children",
          type: "ReactNode",
          en: "`Select.TriggerIcon`, `Select.Value`, optionally a Badge after it.",
          ru: "`Select.TriggerIcon`, `Select.Value`, при необходимости Badge после него.",
        },
      ],
    },
    {
      name: "Select.Value",
      en: "No ref. The picked label (labels joined with `multiple`) with an ellipsis, or the placeholder.",
      ru: "Выбранная подпись (через запятую при `multiple`) или плейсхолдер.",
      props: [
        {
          name: "renderValue",
          type: "(item: { value: string; label: string }) => ReactNode",
          en: "Single mode: draws the picked option in the trigger with the row parts (Thumbnail, ItemText, ItemDescription); not called while empty.",
          ru: "Одиночный выбор: рисует выбранный пункт в триггере частями строки; без значения не вызывается.",
        },
        {
          name: "className",
          type: "string",
          en: "Class on the value.",
          ru: "Класс значения.",
        },
      ],
    },
    {
      name: "Select.TriggerIcon · Select.ItemIcon",
      en: "No ref. An `aria-hidden` `<span>` with a leading glyph at the tier icon size: before the value / before the option label. + native `<span>` props.",
      ru: "Иконка в начале триггера / пункта по размеру яруса; скрыта от скринридеров.",
      props: [],
    },
    {
      name: "Select.Content",
      en: 'No ref. Portal + the floating list panel; stays mounted while closed (the items register their labels), shown with the overlay motion. Holds the search row, the `role="listbox"` and the empty state.',
      ru: "Портал и панель списка; смонтирована и в закрытом виде, чтобы триггер знал подписи.",
      props: [
        {
          name: "searchable",
          type: "boolean",
          default: "false",
          en: "A search field on top; items filter by label, description and `keywords`.",
          ru: "Поле поиска сверху; пункты фильтруются по подписи, описанию и `keywords`.",
        },
        {
          name: "className",
          type: "string",
          en: "Class on the panel.",
          ru: "Класс панели.",
        },
        {
          name: "children",
          type: "ReactNode",
          required: true,
          en: "Items, groups, separators.",
          ru: "Пункты, группы, разделители.",
        },
      ],
    },
    {
      name: "Select.Item",
      en: '`ref` → `HTMLDivElement`. `role="option"` with `aria-selected`; a check on the end (single) or a Checkbox.Indicator in front (`multiple`).',
      ru: 'Пункт `role="option"`: галочка справа или чекбокс слева при `multiple`.',
      props: [
        {
          name: "value",
          type: "string",
          required: true,
          en: "Value of the option.",
          ru: "Значение пункта.",
        },
        {
          name: "label",
          type: "string",
          en: "Text in the trigger and for typeahead; defaults to `Select.ItemText`, then the plain text.",
          ru: "Текст в триггере и для набора с клавиатуры; по умолчанию — `Select.ItemText` или текст пункта.",
        },
        {
          name: "keywords",
          type: "string",
          en: "Extra words for the search.",
          ru: "Дополнительные слова для поиска.",
        },
        {
          name: "disabled",
          type: "boolean",
          default: "false",
          en: "Muted, skipped by the keyboard, not selectable.",
          ru: "Приглушён, клавиатура пропускает, выбрать нельзя.",
        },
        {
          name: "children",
          type: "ReactNode",
          required: true,
          en: "Text, or `Select.ItemIcon`, `Thumbnail.Root`, `Select.ItemText`, `Select.ItemDescription`, `Select.ItemMeta` as direct children.",
          ru: "Текст или части пункта прямыми детьми.",
        },
      ],
    },
    {
      name: "Select.ItemText · Select.ItemDescription · Select.ItemMeta",
      en: "No ref. Rich option parts: the title (its text is the label) / a muted second line (searchable; makes the row two-line) / a trailing muted value before the check. A `Thumbnail.Root` child is the leading media, sized to the tier unless it sets `size`.",
      ru: "Части богатого пункта: заголовок, вторая строка, значение справа; Thumbnail слева.",
      props: [],
    },
    {
      name: "Select.Group",
      en: 'No ref. `<div role="group">` named by its `label`; hidden while the search leaves none of its options. + native `<div>` props.',
      ru: "Группа пунктов с подписью; скрывается, если поиск не оставил в ней пунктов.",
      props: [
        {
          name: "label",
          type: "ReactNode",
          en: "Heading of the group (caption, muted); also its accessible name.",
          ru: "Подпись группы (caption, приглушённая) и её доступное имя.",
        },
      ],
    },
    {
      name: "Select.Separator",
      en: "No ref. A full-bleed Divider between groups; hidden while searching.",
      ru: "Разделитель на всю ширину; скрыт во время поиска.",
      props: [
        {
          name: "className",
          type: "string",
          en: "Extra class on the divider.",
          ru: "Дополнительный класс разделителя.",
        },
      ],
    },
  ],
  labels: [
    {
      key: "search",
      default: "Поиск",
      en: "Placeholder and accessible name of the search field.",
      ru: "Плейсхолдер и имя поля поиска.",
    },
    {
      key: "empty",
      default: "Ничего не найдено",
      en: "Empty state: no items or nothing matches.",
      ru: "Пустое состояние: пунктов нет или ничего не найдено.",
    },
    {
      key: "emptyHint",
      default: "Попробуйте изменить запрос",
      en: 'Second line of the empty state while searching; `""` hides it.',
      ru: "Вторая строка пустого состояния при поиске; пустая строка скрывает её.",
    },
    {
      key: "loading",
      default: "Загрузка…",
      en: "Status row while `loading`.",
      ru: "Строка загрузки при `loading`.",
    },
    {
      key: "clear",
      default: "Очистить",
      en: "Tooltip of the clear segment.",
      ru: "Всплывающая подпись сегмента очистки.",
    },
    {
      key: "optional",
      default: "необязательно",
      en: "Muted marker after the label when `optional`.",
      ru: "Приглушённая пометка после подписи при `optional`.",
    },
  ],
};
