import type { ComponentApi } from "../../../scripts/docs/componentApi";

export const api: ComponentApi = {
  parts: [
    {
      name: "SmartFilter.Root",
      en: "`ref` → `HTMLDivElement`. A `<div>` (flex column) with the state and the context; sets `data-size`.",
      ru: "`<div>` (колонка) с состоянием и контекстом; ставит `data-size`.",
      props: [
        {
          name: "fields",
          type: "readonly SmartFilterField[]",
          required: true,
          en: "Fields of this screen, in display order; empty — only the search. Pass a stable reference.",
          ru: "Поля экрана в порядке показа; пусто — остаётся только поиск. Передавайте стабильную ссылку.",
        },
        {
          name: "value",
          type: "SmartFilterValue",
          en: "Selection per field key, controlled: `{ include, exclude }` per field.",
          ru: "Выбор по ключам полей, управляемо: `{ include, exclude }` на поле.",
        },
        {
          name: "defaultValue",
          type: "SmartFilterValue",
          default: "{}",
          en: "Initial selection, uncontrolled.",
          ru: "Начальный выбор без контроля.",
        },
        {
          name: "onValueChange",
          type: "(value: SmartFilterValue) => void",
          en: "The whole next value; keys of fields this root does not show are kept.",
          ru: "Всё новое значение; ключи полей, которых нет в этом корне, сохраняются.",
        },
        {
          name: "search",
          type: "string",
          en: "Search text, controlled.",
          ru: "Текст поиска, управляемо.",
        },
        {
          name: "defaultSearch",
          type: "string",
          default: '""',
          en: "Initial search text, uncontrolled.",
          ru: "Начальный текст поиска без контроля.",
        },
        {
          name: "onSearchChange",
          type: "(search: string) => void",
          en: "Every keystroke; debounce in the owner when it asks a server.",
          ru: "Каждое нажатие; при запросах к серверу ставьте задержку у владельца.",
        },
        {
          name: "size",
          type: '"xs" | "s" | "m" | "l" | "xl"',
          default: '"m"',
          en: "Tier of the filter button, the search, the tags and the panel.",
          ru: "Ярус кнопки фильтра, поиска, тегов и панели.",
        },
        {
          name: "collapsedLimit",
          type: "number",
          default: "12",
          en: "Values of one field shown before «Ещё N» (not while searching).",
          ru: "Сколько значений поля видно до «Ещё N» (кроме поиска).",
        },
        {
          name: "labels",
          type: "Partial<SmartFilterLabels>",
          en: "Built-in strings, see Labels.",
          ru: "Системные строки, см. «Доступность».",
        },
        {
          name: "className",
          type: "string",
          en: "Class on the root.",
          ru: "Класс корня.",
        },
        {
          name: "children",
          type: "ReactNode",
          required: true,
          en: "`SmartFilter.Toolbar` and `SmartFilter.Chips`, anywhere inside.",
          ru: "`SmartFilter.Toolbar` и `SmartFilter.Chips` в любом месте внутри.",
        },
      ],
    },
    {
      name: "SmartFilter.Toolbar",
      en: "No ref. A `<div>`: the filter Button (a count Badge while filters apply) and a search Input; the anchor of the panel, a flush Popover.",
      ru: "`<div>`: кнопка фильтра (Badge-счётчик при фильтрах) и поле поиска; якорь панели — Popover без внутренних отступов.",
      props: [
        {
          name: "className",
          type: "string",
          en: "Class on the toolbar.",
          ru: "Класс панели инструментов.",
        },
      ],
    },
    {
      name: "SmartFilter.Chips",
      en: "No ref. A `<div>` of applied filters as removable Badges with «Добавить фильтр» and «Сбросить все»; renders nothing without filters.",
      ru: "`<div>` с применёнными фильтрами — удаляемыми Badge — и кнопками «Добавить фильтр», «Сбросить все»; без фильтров ничего не рендерит.",
      props: [
        {
          name: "className",
          type: "string",
          en: "Class on the chips row.",
          ru: "Класс ряда тегов.",
        },
      ],
    },
    {
      name: "SmartFilterField",
      en: "One entry of `fields`: data, not a part. Selected values missing from `options` stay visible so they can be removed.",
      ru: "Один элемент `fields`: данные, а не часть. Выбранные значения, которых нет в `options`, остаются видны, чтобы их можно было убрать.",
      props: [
        {
          name: "key",
          type: "string",
          required: true,
          en: "Key of the field in the value.",
          ru: "Ключ поля в значении.",
        },
        {
          name: "label",
          type: "string",
          required: true,
          en: "Field name in the panel and the chips.",
          ru: "Название поля в панели и тегах.",
        },
        {
          name: "options",
          type: "{ value: string; label: string; icon?: ReactNode }[]",
          required: true,
          en: "Values; `icon` is a decorative kit Icon before the label.",
          ru: "Значения; `icon` — декоративная иконка набора перед подписью.",
        },
        {
          name: "finite",
          type: "boolean",
          default: "true",
          en: "A fixed set: hiding every value is refused. `false` for an open set (services, users).",
          ru: "Фиксированный набор: скрыть все значения нельзя. `false` — для открытого набора (сервисы, пользователи).",
        },
      ],
    },
    {
      name: "matchesSmartFilter · resolveSmartFilterValues",
      en: "Helpers. `matchesSmartFilter(selection, value)` checks one value on the client (`include` empty = any, `exclude` rejects). `resolveSmartFilterValues(selection, all)` turns a fixed field into the list to ask a server for: «hide» becomes «all except», `[]` — no filter.",
      ru: "Помощники. `matchesSmartFilter(selection, value)` проверяет значение на клиенте (пустой `include` — любое, `exclude` отклоняет). `resolveSmartFilterValues(selection, all)` превращает фиксированное поле в список для сервера: «скрыть» — «все, кроме», `[]` — без фильтра.",
      props: [],
    },
  ],
  labels: [
    {
      key: "filter",
      default: "Фильтр",
      en: "Filter button and panel name.",
      ru: "Кнопка фильтра и имя панели.",
    },
    {
      key: "searchPlaceholder",
      default: "Поиск",
      en: "Placeholder and name of the search.",
      ru: "Плейсхолдер и имя поиска.",
    },
    {
      key: "clearSearch",
      default: "Очистить поиск",
      en: "Name of the search clear button.",
      ru: "Имя кнопки очистки поиска.",
    },
    {
      key: "searchText",
      default: "Искать «{query}»",
      en: "The text search row while typing.",
      ru: "Строка текстового поиска при вводе.",
    },
    {
      key: "noMatches",
      default: "{fields} — нет совпадений",
      en: "Fields with nothing found while typing (compact EmptyPage).",
      ru: "Поля без совпадений при вводе (компактный EmptyPage).",
    },
    {
      key: "hint",
      default: "Нажмите значение, чтобы показать только его; «−» справа — скрыть",
      en: "Panel footer hint.",
      ru: "Подсказка в подвале панели.",
    },
    {
      key: "count",
      default: "Фильтров: {count}",
      en: "Panel footer counter.",
      ru: "Счётчик в подвале панели.",
    },
    { key: "reset", default: "Сбросить", en: "Panel footer reset.", ru: "Сброс в подвале панели." },
    {
      key: "more",
      default: "Ещё {count}",
      en: "Collapsed values of a field.",
      ru: "Свёрнутые значения поля.",
    },
    {
      key: "add",
      default: "Добавить фильтр",
      en: "Chips row: opens the panel.",
      ru: "Ряд тегов: открывает панель.",
    },
    {
      key: "clearAll",
      default: "Сбросить все",
      en: "Chips row: clears every field.",
      ru: "Ряд тегов: сбрасывает все поля.",
    },
    {
      key: "showValue",
      default: "Показать только {value}",
      en: "Title of a value.",
      ru: "Подсказка значения.",
    },
    {
      key: "hideValue",
      default: "Скрыть {value}",
      en: "Name of the «−» of a value.",
      ru: "Имя «−» у значения.",
    },
    {
      key: "unhideValue",
      default: "Не скрывать {value}",
      en: "Name of the «−» of a hidden value.",
      ru: "Имя «−» у скрытого значения.",
    },
    {
      key: "not",
      default: "НЕ",
      en: "Prefix of a hidden value.",
      ru: "Префикс скрытого значения.",
    },
    {
      key: "chipInclude",
      default: "{field}: {value}",
      en: "Text of a «show» tag.",
      ru: "Текст тега «показать».",
    },
    {
      key: "chipExclude",
      default: "{field}: не {value}",
      en: "Text of a «hide» tag.",
      ru: "Текст тега «скрыть».",
    },
    {
      key: "remove",
      default: "Убрать фильтр «{value}»",
      en: "Name of a tag's remove button.",
      ru: "Имя кнопки удаления тега.",
    },
  ],
};
