import type { ComponentApi } from "../../../scripts/docs/componentApi";
import { FIELD_ROOT_REST } from "../../internal/field.api";

export const api: ComponentApi = {
  parts: [
    {
      name: "Datepicker.Root",
      en: "`ref` → `HTMLDivElement` (the field frame). A field (label, hint / error, the field button with a calendar icon, the value and a chevron) that opens the calendar panel in a Popover. Takes every calendar option below.",
      ru: "Поле (подпись, подсказка или ошибка, кнопка поля с иконкой календаря, значение и шеврон), которое открывает панель календаря в Popover. Принимает все параметры календаря ниже.",
      props: [
        {
          name: "mode",
          type: '"single" | "range"',
          required: true,
          en: "One date or a period; sets the value type.",
          ru: "Одна дата или период; задаёт тип значения.",
        },
        {
          name: "value",
          type: "Date | null  ·  DatepickerRange",
          en: "Controlled value: a date (`single`) or `{ from, to }` in wall-clock time (`range`); `null` — not set.",
          ru: "Значение, управляемо: дата (`single`) или `{ from, to }` в «настенном» времени (`range`); `null` — не задано.",
        },
        {
          name: "defaultValue",
          type: "Date | null  ·  DatepickerRange",
          default: "null · { from: null, to: null }",
          en: "Initial value, uncontrolled.",
          ru: "Начальное значение без контроля.",
        },
        {
          name: "onValueChange",
          type: "(value) => void",
          en: "Called when a pick, a preset, Apply or Reset changes the value.",
          ru: "Выбор дня, пресет, «Применить» или «Сбросить» меняют значение.",
        },
        {
          name: "open",
          type: "boolean",
          en: "Controlled visibility of the panel.",
          ru: "Видимость панели, управляемо.",
        },
        {
          name: "defaultOpen",
          type: "boolean",
          default: "false",
          en: "Initial visibility, uncontrolled.",
          ru: "Начальная видимость без контроля.",
        },
        {
          name: "onOpenChange",
          type: "(open: boolean) => void",
          en: "Field click, Escape, an outside press or an applied value.",
          ru: "Клик по полю, Escape, нажатие снаружи или применённое значение.",
        },
        {
          name: "size",
          type: '"xs" | "s" | "m" | "l" | "xl"',
          default: '"m"',
          en: "Field tier (height 28 · 32 · 36 · 40 · 48) and panel tier (day cell 24 · 28 · 32 · 36 · 40).",
          ru: "Ярус поля (высота 28 · 32 · 36 · 40 · 48) и панели (клетка дня 24 · 28 · 32 · 36 · 40).",
        },
        {
          name: "label",
          type: "ReactNode",
          en: "Field label; part of the button's accessible name together with the value.",
          ru: "Подпись поля; вместе со значением — доступное имя кнопки.",
        },
        {
          name: "hint",
          type: "ReactNode",
          en: "Support text under the field (`aria-describedby`).",
          ru: "Подсказка под полем (`aria-describedby`).",
        },
        {
          name: "error",
          type: "ReactNode",
          en: "Error message in place of the hint; implies `invalid`.",
          ru: "Ошибка на месте подсказки; включает `invalid`.",
        },
        {
          name: "required",
          type: "boolean",
          default: "false",
          en: "Red `*` after the label.",
          ru: "Красная `*` после подписи.",
        },
        {
          name: "optional",
          type: "boolean",
          en: "Muted `labels.optional` after the label.",
          ru: "Приглушённое `labels.optional` после подписи.",
        },
        {
          name: "invalid",
          type: "boolean",
          en: "Danger ring and `aria-invalid` without a message.",
          ru: "Красное кольцо и `aria-invalid` без текста ошибки.",
        },
        {
          name: "disabled",
          type: "boolean",
          default: "false",
          en: "The field cannot be opened.",
          ru: "Поле нельзя открыть.",
        },
        {
          name: "fullWidth",
          type: "boolean",
          default: "false",
          en: "The field stretches to its container; otherwise it fits the text.",
          ru: "Поле на всю ширину контейнера; иначе — по тексту.",
        },
        {
          name: "align",
          type: '"start" | "center" | "end"',
          default: '"start"',
          en: "Popover alignment to the field.",
          ru: "Выравнивание поповера относительно поля.",
        },
        {
          name: "focusRing",
          type: "boolean",
          default: "true",
          en: '`false` hides only the visual focus ring (`data-focus-ring="false"`).',
          ru: '`false` скрывает только видимое кольцо фокуса (`data-focus-ring="false"`).',
        },
        {
          name: "placeholder",
          type: "string",
          default: "labels.placeholder",
          en: "Field text without a value for this field.",
          ru: "Текст поля без значения для этого поля.",
        },
        {
          name: "valuePrefix",
          type: "string",
          en: "Text before the value, e.g. «С».",
          ru: "Текст перед значением, например «С».",
        },
        {
          name: "id",
          type: "string",
          en: "Id of the field button; generated when omitted.",
          ru: "Id кнопки поля; без него генерируется.",
        },
        {
          name: "aria-label · aria-labelledby · aria-describedby",
          type: "string",
          en: "Name without a `label` (the value is appended) and extra description ids.",
          ru: "Имя без `label` (значение добавляется) и дополнительные id описания.",
        },
        FIELD_ROOT_REST,
      ],
    },
    {
      name: "Datepicker.Panel",
      en: "`ref` → `HTMLDivElement`. The calendar without a field, inline in a page: its own card, 1–2 months by the parent's width. Takes `mode`, `value` / `defaultValue` / `onValueChange` like Root and every calendar option below.",
      ru: "Календарь без поля прямо на странице: своя карточка, 1–2 месяца по ширине родителя. Принимает `mode`, `value` / `defaultValue` / `onValueChange`, как Root, и все параметры календаря ниже.",
      props: [
        {
          name: "…rest",
          type: 'Omit<HTMLAttributes<HTMLDivElement>, "children" | "defaultValue" | "defaultChecked" | "onChange">',
          en: "`className` and the other attributes of the panel card.",
          ru: "`className` и остальные атрибуты карточки панели.",
        },
      ],
    },
    {
      name: "Calendar options (Root · Panel)",
      en: "Shared by `Datepicker.Root` and `Datepicker.Panel`.",
      ru: "Общие для `Datepicker.Root` и `Datepicker.Panel`.",
      props: [
        {
          name: "months",
          type: "1 | 2",
          default: "1",
          en: "Months side by side; one when there is no room.",
          ru: "Сколько месяцев рядом; если места мало — один.",
        },
        {
          name: "presets",
          type: "DatepickerPreset[] | false",
          default: "false",
          en: "Preset column (`range` only): `DEFAULT_DATEPICKER_PRESETS` or picks from `datepickerPresets`; a row above the calendar when narrow.",
          ru: "Колонка периодов (только `range`): `DEFAULT_DATEPICKER_PRESETS` или выборка из `datepickerPresets`; на узком — строкой над календарём.",
        },
        {
          name: "prompt",
          type: "boolean",
          default: "false",
          en: "Step prompt under the calendar (`labels.pickStart` / `pickEnd` / `pickDate`).",
          ru: "Подсказка шага под календарём (`labels.pickStart` / `pickEnd` / `pickDate`).",
        },
        {
          name: "footer",
          type: "boolean",
          default: "false",
          en: "Footer with date fields and Reset / Apply; without it a pick applies at once.",
          ru: "Нижняя строка с датами и «Сбросить» / «Применить»; без неё выбор применяется сразу.",
        },
        {
          name: "withTime",
          type: "boolean",
          default: "false",
          en: "Time fields in the footer (00:00 — 23:59 by default).",
          ru: "Поля времени в нижней строке (по умолчанию 00:00 — 23:59).",
        },
        {
          name: "isDayDisabled",
          type: "(day: Date) => boolean",
          en: "Days that cannot be picked.",
          ru: "Дни, которые нельзя выбрать.",
        },
        {
          name: "disableFuture",
          type: "boolean",
          default: "false",
          en: "Future days are muted and cannot be picked.",
          ru: "Будущие дни приглушены и недоступны.",
        },
        {
          name: "yearless",
          type: "boolean",
          default: "false",
          en: "An annual day + month: no year, months wrap around inside `YEARLESS_YEAR`.",
          ru: "Ежегодная дата «день + месяц»: без года, листание по кругу в `YEARLESS_YEAR`.",
        },
        {
          name: "resetValue",
          type: "Date | null  ·  DatepickerRange",
          default: "null · { from: null, to: null }",
          en: "Value applied by Reset.",
          ru: "Значение, которое ставит «Сбросить».",
        },
        {
          name: "today",
          type: "Date",
          default: "new Date()",
          en: "«Today» for highlighting, presets and `disableFuture`.",
          ru: "«Сегодня» для подсветки, пресетов и `disableFuture`.",
        },
        {
          name: "locale",
          type: "Locale",
          default: "ru",
          en: "date-fns locale of titles, weekdays and day names.",
          ru: "Локаль date-fns для заголовков, дней недели и имён дней.",
        },
        {
          name: "weekStartsOn",
          type: "0 | 1 | 2 | 3 | 4 | 5 | 6",
          default: "1",
          en: "First day of the week (1 — Monday).",
          ru: "Первый день недели (1 — понедельник).",
        },
        {
          name: "labels",
          type: "Partial<DatepickerLabels>",
          en: "Built-in strings, see Labels.",
          ru: "Системные строки, см. «Доступность».",
        },
      ],
    },
  ],
  labels: [
    {
      key: "placeholder",
      default: "Выбрать дату",
      en: "Field text without a value.",
      ru: "Текст поля без значения.",
    },
    {
      key: "pickStart",
      default: "Выберите начальную дату",
      en: "Step prompt before the start of a range.",
      ru: "Подсказка до выбора начала периода.",
    },
    {
      key: "pickEnd",
      default: "Выберите конечную дату",
      en: "Step prompt before the end of a range.",
      ru: "Подсказка до выбора конца периода.",
    },
    {
      key: "pickDate",
      default: "Выберите дату",
      en: "Step prompt of a single date.",
      ru: "Подсказка для одной даты.",
    },
    { key: "reset", default: "Сбросить", en: "Footer reset button.", ru: "Кнопка сброса." },
    { key: "apply", default: "Применить", en: "Footer apply button.", ru: "Кнопка применения." },
    {
      key: "prevMonth",
      default: "Предыдущий месяц",
      en: "Name of the previous-month arrow.",
      ru: "Имя стрелки к предыдущему месяцу.",
    },
    {
      key: "nextMonth",
      default: "Следующий месяц",
      en: "Name of the next-month arrow.",
      ru: "Имя стрелки к следующему месяцу.",
    },
    {
      key: "rangeStart",
      default: "Начало периода",
      en: "Name of the footer start field.",
      ru: "Имя поля начала в нижней строке.",
    },
    {
      key: "rangeEnd",
      default: "Конец периода",
      en: "Name of the footer end field.",
      ru: "Имя поля конца в нижней строке.",
    },
    {
      key: "date",
      default: "Дата",
      en: "Name of the footer field of a single date.",
      ru: "Имя поля одной даты в нижней строке.",
    },
    {
      key: "timeStart",
      default: "Время начала",
      en: "Name of the start time input.",
      ru: "Имя поля времени начала.",
    },
    {
      key: "timeEnd",
      default: "Время конца",
      en: "Name of the end time input.",
      ru: "Имя поля времени конца.",
    },
    {
      key: "time",
      default: "Время",
      en: "Name of the time input of a single date.",
      ru: "Имя поля времени одной даты.",
    },
    {
      key: "until",
      default: "до",
      en: "Prefix of a range without a start: «до 6 окт».",
      ru: "Префикс периода без начала: «до 6 окт».",
    },
    {
      key: "presetsTitle",
      default: "Период",
      en: "Heading and group name of the presets column.",
      ru: "Заголовок и имя группы колонки периодов.",
    },
    {
      key: "optional",
      default: "необязательно",
      en: "Muted marker after the label when `optional`.",
      ru: "Приглушённая пометка после подписи при `optional`.",
    },
  ],
};
