/**
 * Adds kit glyphs drawn from Lucide: writes `src/icons/glyphs/<kebab>.tsx` with the glyph's path
 * data copied verbatim from `lucide-react`, ready for its gesture (`data-motion`, see
 * `src/icons/glyphMotion.module.css`) and a registry entry in `src/icons/registry.ts`.
 *
 *   bun run icons:add Bell ShoppingCart        # a Lucide export name or its kebab file name (shopping-cart)
 *   bun run icons:add --out playground/icons/glyphs SquareKanban   # a docs-only glyph
 *
 * Existing files are left untouched; aliases resolve to the canonical Lucide name. Every run (with
 * no names too) regenerates `src/icon-set.ts`, the `prime-ui-kit/icons` entry: one `<Name>Icon` export
 * per kit glyph file.
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const args = process.argv.slice(2);
const outFlag = args.indexOf("--out");
const outDir = outFlag === -1 ? "src/icons/glyphs" : args[outFlag + 1];
const names = outFlag === -1 ? args : args.filter((_, i) => i !== outFlag && i !== outFlag + 1);

const root = join(import.meta.dirname, "..");
const lucideDir = join(root, "node_modules/lucide-react/dist/esm");
const index = readFileSync(join(lucideDir, "lucide-react.js"), "utf8");
const glyphModule = outDir === "src/icons/glyphs" ? "../glyph" : "@/icons/glyph";

/** Lucide export name (with every alias) → icon file. */
const fileOf = new Map<string, string>();
for (const m of index.matchAll(/export \{([^}]*)\} from '\.\/icons\/([\w-]+)\.js'/g)) {
  for (const part of m[1].split(",")) {
    const alias = part.trim().split(/\s+as\s+/)[1];
    if (alias) fileOf.set(alias, m[2]);
  }
}

const pascal = (kebab: string) =>
  kebab
    .split("-")
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join("");
const camel = (attr: string) => attr.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

mkdirSync(join(root, outDir), { recursive: true });
for (const name of names) {
  let kebab =
    fileOf.get(name) ?? (existsSync(join(lucideDir, `icons/${name}.js`)) ? name : undefined);
  if (!kebab) throw new Error(`lucide-react has no icon "${name}"`);
  let source = readFileSync(join(lucideDir, `icons/${kebab}.js`), "utf8");
  // A renamed icon's old file only re-exports the new one: follow it to the drawing.
  for (let alias = source.match(/export \{ default \} from '\.\/([\w-]+)\.js'/); alias; ) {
    kebab = alias[1];
    source = readFileSync(join(lucideDir, `icons/${kebab}.js`), "utf8");
    alias = source.match(/export \{ default \} from '\.\/([\w-]+)\.js'/);
  }
  const canonical = pascal(kebab);
  const target = join(root, outDir, `${kebab}.tsx`);
  if (existsSync(target)) {
    console.log(`exists  ${relative(root, target)} (${canonical})`);
    continue;
  }
  const nodeSource = source.match(/const __iconNode = (\[[\s\S]*?\]);\nconst/)?.[1];
  if (!nodeSource) throw new Error(`cannot read the drawing of "${kebab}"`);
  const node = new Function(`return ${nodeSource}`)() as [string, Record<string, string>][];
  const elements = node.map(([tag, attrs]) => {
    const props = Object.entries(attrs)
      .filter(([key]) => key !== "key")
      .map(([key, value]) => `${camel(key)}="${value}"`)
      .join(" ");
    return `<${tag} ${props} />`;
  });
  const body = elements.length === 1 ? elements[0] : `<>\n    ${elements.join("\n    ")}\n  </>`;
  writeFileSync(
    target,
    `import { defineGlyph } from "${glyphModule}";

/** Lucide \`${kebab}\`: <its gesture>. */
export const ${canonical} = /* @__PURE__ */ defineGlyph(
  "${canonical}",
  ${body},
);
`,
  );
  console.log(`added   ${relative(root, target)} (${canonical}) — give it a gesture`);
}

/** `prime-ui-kit/icons`: every kit glyph as `<Name>Icon`, in file order. */
const kitGlyphs = join(root, "src/icons/glyphs");
const exportsOf = readdirSync(kitGlyphs)
  .filter((file) => file.endsWith(".tsx"))
  .sort()
  .map((file) => {
    const name = readFileSync(join(kitGlyphs, file), "utf8").match(/export const (\w+) =/)?.[1];
    if (!name) throw new Error(`no glyph export in ${file}`);
    return `export { ${name} as ${name}Icon } from "./icons/glyphs/${file.slice(0, -4)}";`;
  });
writeFileSync(
  join(root, "src/icon-set.ts"),
  `/**
 * \`prime-ui-kit/icons\` — the full animated glyph set as named components (\`<BellIcon />\`), each a
 * Lucide drawing with one gesture; import only what you use, the rest is never bundled. The
 * semantic \`<Icon name>\` set lives in the main entry. Generated by \`bun run icons:add\`.
 */
export type { DomainIconProps as GlyphIconProps, Glyph } from "./icons/glyph";
${exportsOf.join("\n")}
`,
);
// Biome owns the order and wrapping of the generated file (and of the new glyph files).
spawnSync("bunx", ["biome", "check", "--write", "src/icon-set.ts", outDir], { cwd: root });
console.log(`entry   src/icon-set.ts (${exportsOf.length} glyphs)`);
