/**
 * `bun run tokens:build` — `tokens/*.ts` → `src/styles/{tokens,theme-light,theme-dark}.css`.
 * Light is `semantic.ts` itself; dark is `semantic.ts` with `themes/dark.ts` laid over it, and its
 * file keeps only what differs from light.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";

import { REF_PREFIX, SYS_PREFIX, toVarName } from "../tokens/naming";
import { primitiveTokens } from "../tokens/primitives";
import { semanticTokens } from "../tokens/semantic";
import { darkThemeOverrides } from "../tokens/themes/dark";

type TokenTree = { readonly [key: string]: string | number | TokenTree };
type FlatTokens = Record<string, string>;

const HEADER = "/* AUTO-GENERATED by scripts/build-tokens.ts */\n";

/** `{ color: { bg: { canvas: "…" } } }` → `{ "color.bg.canvas": "…" }`. */
function flatten(tree: TokenTree, prefix = ""): FlatTokens {
  const out: FlatTokens = {};
  for (const [key, value] of Object.entries(tree)) {
    const next = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "object") Object.assign(out, flatten(value, next));
    else out[next] = String(value);
  }
  return out;
}

const primitives = flatten(primitiveTokens);
const semantic = flatten(semanticTokens);
const darkOverrides = flatten(darkThemeOverrides);

const unknown = Object.keys(darkOverrides).filter((key) => !(key in semantic));
if (unknown.length > 0) {
  throw new Error(`Dark theme overrides unknown semantic paths:\n- ${unknown.join("\n- ")}`);
}

/** `{path}` → `var(--prime-ref-…)` (a primitive) or `var(--prime-…)` (a semantic token). */
function resolve(value: string): string {
  const ref = /^\{(.+)\}$/.exec(value)?.[1];
  if (ref === undefined) return value;
  if (ref in primitives) return `var(${toVarName(ref, REF_PREFIX)})`;
  if (ref in semantic) return `var(${toVarName(ref, SYS_PREFIX)})`;
  throw new Error(`Unknown token reference: ${value}`);
}

function cssBlock(selector: string, tokens: FlatTokens, prefix: string): string {
  const lines = Object.entries(tokens)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `  ${toVarName(key, prefix)}: ${resolve(value)};`);
  return `${HEADER}${selector} {\n${lines.join("\n")}\n}\n`;
}

const dark = { ...semantic, ...darkOverrides };
const darkOnly = Object.fromEntries(
  Object.entries(dark).filter(([key, value]) => semantic[key] !== value),
);

const stylesDir = path.resolve(import.meta.dirname, "../src/styles");
await Promise.all([
  writeFile(path.join(stylesDir, "tokens.css"), cssBlock(":root", primitives, REF_PREFIX)),
  writeFile(
    path.join(stylesDir, "theme-light.css"),
    cssBlock(':root,\n:root[data-theme="light"],\n[data-theme="light"]', semantic, SYS_PREFIX),
  ),
  writeFile(
    path.join(stylesDir, "theme-dark.css"),
    cssBlock(':root[data-theme="dark"],\n[data-theme="dark"]', darkOnly, SYS_PREFIX),
  ),
]);
