import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { primitiveTokens } from "../tokens/primitives";
import { semanticTokens } from "../tokens/semantic";
import { darkThemeOverrides } from "../tokens/themes/dark";
import { lightThemeOverrides } from "../tokens/themes/light";

type AnyTokenValue = string | number | { [key: string]: AnyTokenValue };
type FlatTokens = Record<string, string>;

const REF_PREFIX = "--prime-ref";
const SYS_PREFIX = "--prime-sys";

function flattenTokens(input: { [key: string]: AnyTokenValue }, prefix = ""): FlatTokens {
  const output: FlatTokens = {};

  for (const [key, value] of Object.entries(input)) {
    const nextKey = prefix ? `${prefix}.${key}` : key;

    if (value !== null && typeof value === "object") {
      Object.assign(output, flattenTokens(value as { [key: string]: AnyTokenValue }, nextKey));
      continue;
    }

    output[nextKey] = String(value);
  }

  return output;
}

function flattenPartialTokens(input: unknown, prefix = ""): FlatTokens {
  if (typeof input !== "object" || input === null) {
    return {};
  }

  const objectInput = input as Record<string, unknown>;
  const output: FlatTokens = {};

  for (const [key, value] of Object.entries(objectInput)) {
    const nextKey = prefix ? `${prefix}.${key}` : key;

    if (value !== null && typeof value === "object") {
      Object.assign(output, flattenPartialTokens(value, nextKey));
      continue;
    }

    if (typeof value === "string" || typeof value === "number") {
      output[nextKey] = String(value);
    }
  }

  return output;
}

function mergeTokens(base: FlatTokens, overrides: FlatTokens): FlatTokens {
  return { ...base, ...overrides };
}

function validateOverridePaths(
  base: FlatTokens,
  overrides: FlatTokens,
  themeName: "light" | "dark",
): void {
  const baseKeys = new Set(Object.keys(base));
  const unknownOverridePaths: string[] = [];

  for (const overridePath of Object.keys(overrides)) {
    if (!baseKeys.has(overridePath)) {
      unknownOverridePaths.push(overridePath);
    }
  }

  if (unknownOverridePaths.length > 0) {
    throw new Error(
      `[prime-ui-kit] Theme "${themeName}" overrides unknown semantic token paths:\n- ${unknownOverridePaths.join("\n- ")}`,
    );
  }
}

function toVarName(pathKey: string, prefix: string): string {
  return `${prefix}-${pathKey.replaceAll(".", "-")}`;
}

function resolveTokenValue(
  value: string,
  primitiveVarsByPath: Record<string, string>,
  semanticVarsByPath: Record<string, string>,
): string {
  const refMatch = value.match(/^\{(.+)\}$/);
  if (!refMatch) {
    return value;
  }

  const refPath = refMatch[1];
  const primitiveVar = primitiveVarsByPath[refPath];
  if (primitiveVar) {
    return `var(${primitiveVar})`;
  }

  const semanticVar = semanticVarsByPath[refPath];
  if (semanticVar) {
    return `var(${semanticVar})`;
  }

  throw new Error(`Unknown token reference: ${value}`);
}

function toCssBlock(selector: string, tokens: FlatTokens, varPrefix: string): string {
  const lines = Object.entries(tokens)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => `  ${toVarName(key, varPrefix)}: ${value};`);

  return `${selector} {\n${lines.join("\n")}\n}\n`;
}

async function buildTokens(): Promise<void> {
  const primitiveFlat = flattenTokens(primitiveTokens);
  const semanticFlat = flattenTokens(semanticTokens);
  const lightOverrideFlat = flattenPartialTokens(lightThemeOverrides);
  const darkOverrideFlat = flattenPartialTokens(darkThemeOverrides);

  validateOverridePaths(semanticFlat, lightOverrideFlat, "light");
  validateOverridePaths(semanticFlat, darkOverrideFlat, "dark");

  const primitiveVarsByPath: Record<string, string> = {};
  for (const pathKey of Object.keys(primitiveFlat)) {
    primitiveVarsByPath[pathKey] = toVarName(pathKey, REF_PREFIX);
  }

  const semanticVarsByPath: Record<string, string> = {};
  for (const pathKey of Object.keys(semanticFlat)) {
    semanticVarsByPath[pathKey] = toVarName(pathKey, SYS_PREFIX);
  }

  const resolveSemanticMap = (source: FlatTokens): FlatTokens => {
    const resolved: FlatTokens = {};
    for (const [pathKey, value] of Object.entries(source)) {
      resolved[pathKey] = resolveTokenValue(value, primitiveVarsByPath, semanticVarsByPath);
    }
    return resolved;
  };

  const lightSemantic = resolveSemanticMap(mergeTokens(semanticFlat, lightOverrideFlat));
  const darkSemantic = resolveSemanticMap(mergeTokens(semanticFlat, darkOverrideFlat));

  const stylesDir = path.resolve(process.cwd(), "src/styles");
  await mkdir(stylesDir, { recursive: true });

  const tokensCss = `/* AUTO-GENERATED by scripts/build-tokens.ts */\n${toCssBlock(
    ":root",
    primitiveFlat,
    REF_PREFIX,
  )}`;

  const themeLightCss =
    "/* AUTO-GENERATED by scripts/build-tokens.ts */\n" +
    toCssBlock(
      ':root,\n:root[data-theme="light"],\n[data-theme="light"]',
      lightSemantic,
      SYS_PREFIX,
    );

  const themeDarkCss =
    "/* AUTO-GENERATED by scripts/build-tokens.ts */\n" +
    toCssBlock(':root[data-theme="dark"],\n[data-theme="dark"]', darkSemantic, SYS_PREFIX);

  await Promise.all([
    writeFile(path.join(stylesDir, "tokens.css"), tokensCss),
    writeFile(path.join(stylesDir, "theme-light.css"), themeLightCss),
    writeFile(path.join(stylesDir, "theme-dark.css"), themeDarkCss),
  ]);
}

buildTokens().catch((error: unknown) => {
  console.error("[prime-ui-kit] Failed to build tokens", error);
  process.exitCode = 1;
});
