import type { ComponentApi } from "../../../scripts/docs/componentApi";

export const api: ComponentApi = {
  parts: [
    {
      name: "DataTable",
      en: "Generic over `Row`; `ref` → `HTMLDivElement`. A card-fill block with an optional toolbar, a scrolling `<table>` and a footer (range, Pagination, infinite-scroll status); passes its tier to the controls inside.",
      ru: "Блок с заливкой карточки: панель сверху, прокручиваемая `<table>` и подвал (диапазон, Pagination, статус догрузки); передаёт ярус контролам внутри.",
      props: [
        {
          name: "columns",
          type: "DataTableColumn<Row>[]",
          required: true,
          en: "Column definitions, see `DataTableColumn<Row>`.",
          ru: "Описание колонок, см. `DataTableColumn<Row>`.",
        },
        {
          name: "hiddenColumns",
          type: "string[]",
          en: "Ids of columns that are not rendered (head, body, skeleton and state rows); widths are measured again. A column with `hideable: false` stays. The list and the control that changes it (a column chooser in `toolbar`) belong to the consumer; sorting by a hidden column keeps the row order.",
          ru: "Id колонок, которые не выводятся (шапка, тело, скелетоны и строки состояний); ширины измеряются заново. Колонка с `hideable: false` остаётся. Список и контрол, который его меняет (выбор колонок в `toolbar`), — у потребителя; сортировка по скрытой колонке сохраняет порядок строк.",
        },
        {
          name: "rows",
          type: "Row[]",
          required: true,
          en: "Data; sorted in memory when a sort is set.",
          ru: "Данные; сортируются в памяти, когда задана сортировка.",
        },
        {
          name: "getRowKey",
          type: "(row: Row, index: number) => Key",
          en: "Stable row id (position by default); selection, expansion and the enter animation of new rows are keyed by it. Pass it whenever sorting, selection or expansion is used.",
          ru: "Стабильный id строки (по умолчанию — позиция); по нему выбор, раскрытие и анимация новых строк. Нужен при сортировке, выборе и раскрытии.",
        },
        {
          name: "getRowLabel",
          type: "(row: Row) => string",
          en: "Human row name for the checkbox and toggle names (`{label}` in `labels`).",
          ru: "Имя строки для подписей флажка и переключателя (`{label}` в `labels`).",
        },
        {
          name: "size",
          type: '"xs" | "s" | "m" | "l" | "xl"',
          default: '"m"',
          en: "Density and control tier: rows from 36 · 36 · 44 · 52 · 52 px; passed to checkboxes, toggles, Pagination and nested controls.",
          ru: "Плотность и ярус: строки от 36 · 36 · 44 · 52 · 52 px; передаётся флажкам, переключателям, Pagination и контролам в ячейках.",
        },
        {
          name: "paging",
          type: '"pages" | "infinite" | "none"',
          default: '"pages"',
          en: "`pages` — Pagination in the footer when there is more than one page; `infinite` — rows are revealed while scrolling; `none` — every row at once.",
          ru: "`pages` — Pagination в подвале, если страниц больше одной; `infinite` — строки догружаются при прокрутке; `none` — все строки сразу.",
        },
        {
          name: "pageSize",
          type: "number",
          default: "10",
          en: 'Rows per page; also the first batch with `paging="infinite"`.',
          ru: 'Строк на странице; при `paging="infinite"` — первая порция.',
        },
        {
          name: "page",
          type: "number",
          en: "Current page (1-based), controlled.",
          ru: "Текущая страница (с 1), управляемо.",
        },
        {
          name: "defaultPage",
          type: "number",
          default: "1",
          en: "Initial page, uncontrolled.",
          ru: "Начальная страница без контроля.",
        },
        {
          name: "onPageChange",
          type: "(page: number) => void",
          en: "Page change from the pager; a sort change also returns to page 1.",
          ru: "Смена страницы; смена сортировки тоже возвращает на первую.",
        },
        {
          name: "sort",
          type: "DataTableSortState",
          en: 'Current sort, controlled: `{ columnId, order: "asc" | "desc" }` or `null`.',
          ru: 'Текущая сортировка, управляемо: `{ columnId, order: "asc" | "desc" }` или `null`.',
        },
        {
          name: "defaultSort",
          type: "DataTableSortState",
          default: "null",
          en: "Initial sort, uncontrolled.",
          ru: "Начальная сортировка без контроля.",
        },
        {
          name: "onSortChange",
          type: "(sort: DataTableSortState) => void",
          en: "A head click cycles asc → desc → none.",
          ru: "Клик по заголовку: по возрастанию → по убыванию → без сортировки.",
        },
        {
          name: "loading",
          type: "boolean",
          default: "false",
          en: "Skeleton rows while there are no rows; with rows only `aria-busy`.",
          ru: "Строки-скелетоны, пока строк нет; при строках — только `aria-busy`.",
        },
        {
          name: "loadingRows",
          type: "number",
          default: "min(pageSize, 5)",
          en: "Number of skeleton rows.",
          ru: "Число строк-скелетонов.",
        },
        {
          name: "empty",
          type: "ReactNode",
          default: "labels.empty",
          en: "Empty-state content: a string goes into a compact EmptyPage, a node (e.g. a full `EmptyPage`) is rendered as is.",
          ru: "Пустое состояние: строка попадает в компактный EmptyPage, узел (например, полный `EmptyPage`) выводится как есть.",
        },
        {
          name: "error",
          type: "ReactNode",
          en: 'Load error: replaces the body with the message in `role="alert"`.',
          ru: 'Ошибка загрузки: тело таблицы заменяется сообщением в `role="alert"`.',
        },
        {
          name: "toolbar",
          type: "ReactNode",
          en: "Panel above the table (search, filters, bulk actions); stacks below 30rem of table width.",
          ru: "Панель над таблицей (поиск, фильтры, массовые действия); уже 30rem — в столбик.",
        },
        {
          name: "selectable",
          type: "boolean",
          default: "false",
          en: "Leading checkbox column with «select all», Shift range, press-and-drag and Space.",
          ru: "Колонка флажков: «выбрать все», диапазон с Shift, протяжка и Space.",
        },
        {
          name: "selected",
          type: "Key[]",
          en: "Selected row ids, controlled.",
          ru: "Выбранные id строк, управляемо.",
        },
        {
          name: "defaultSelected",
          type: "Key[]",
          default: "[]",
          en: "Initially selected ids, uncontrolled.",
          ru: "Изначально выбранные id без контроля.",
        },
        {
          name: "onSelectedChange",
          type: "(selected: Key[]) => void",
          en: "Selection change.",
          ru: "Смена выбора.",
        },
        {
          name: "getRowChildren",
          type: "(row: Row) => Row[] | undefined",
          en: "Sub-rows rendered under the parent with the same columns, indented by depth.",
          ru: "Вложенные строки под родителем с теми же колонками и отступом по глубине.",
        },
        {
          name: "renderExpanded",
          type: "(row: Row) => ReactNode",
          en: "Full-width detail row under an expanded row.",
          ru: "Строка деталей на всю ширину под раскрытой строкой.",
        },
        {
          name: "isRowExpandable",
          type: "(row: Row) => boolean",
          en: "Which rows get an expand toggle; by default rows with sub-rows, or every row with `renderExpanded`.",
          ru: "Каким строкам нужен переключатель; по умолчанию — со вложенными строками или всем при `renderExpanded`.",
        },
        {
          name: "expanded",
          type: "Key[]",
          en: "Expanded row ids, controlled.",
          ru: "Раскрытые id строк, управляемо.",
        },
        {
          name: "defaultExpanded",
          type: "Key[]",
          default: "[]",
          en: "Initially expanded ids, uncontrolled.",
          ru: "Изначально раскрытые id без контроля.",
        },
        {
          name: "onExpandedChange",
          type: "(expanded: Key[]) => void",
          en: "Expansion change.",
          ru: "Смена раскрытых строк.",
        },
        {
          name: "infiniteBatchSize",
          type: "number",
          default: "20",
          en: "Rows revealed per scroll step.",
          ru: "Сколько строк добавить за шаг прокрутки.",
        },
        {
          name: "hasMore",
          type: "boolean",
          default: "false",
          en: "More rows can be loaded from the server.",
          ru: "С сервера можно догрузить ещё строки.",
        },
        {
          name: "loadingMore",
          type: "boolean",
          default: "false",
          en: "A server batch is loading: footer status, `aria-busy`.",
          ru: "Идёт догрузка с сервера: статус в подвале, `aria-busy`.",
        },
        {
          name: "onLoadMore",
          type: "() => void | Promise<void>",
          en: "Called at the end when every loaded row is shown and `hasMore` is set.",
          ru: "Вызывается в конце, когда все загруженные строки показаны и `hasMore`.",
        },
        {
          name: "scrollHeight",
          type: "number | string",
          default: '360 with paging="infinite"',
          en: "Max height of the scroll viewport (number = px).",
          ru: "Максимальная высота области прокрутки (число — px).",
        },
        {
          name: "stickyHeader",
          type: "boolean",
          default: "false",
          en: "The head sticks while the body scrolls (with `scrollHeight`); on screens lower than 480px it scrolls with the rows.",
          ru: "Шапка остаётся видимой при прокрутке (со `scrollHeight`); на экранах ниже 480px прокручивается вместе со строками.",
        },
        {
          name: "stickyFirstColumn",
          type: "boolean",
          default: "false",
          en: "The first visible column (with the selection and toggle columns) sticks while scrolling sideways; the start edge shadow falls from its end edge.",
          ru: "Первая видимая колонка (с колонками выбора и раскрытия) закреплена при горизонтальной прокрутке; тень начального края падает от её конца.",
        },
        {
          name: "showHeader",
          type: "boolean",
          default: "true",
          en: "Render `<thead>`.",
          ru: "Показывать `<thead>`.",
        },
        {
          name: "fullWidth",
          type: "boolean",
          default: "true",
          en: "The table spans its container; `false` sizes it by its content.",
          ru: "Таблица на всю ширину контейнера; `false` — по содержимому.",
        },
        {
          name: "rowDividers",
          type: "boolean",
          default: "true",
          en: "Hairlines between rows.",
          ru: "Тонкие линии между строками.",
        },
        {
          name: "columnDividers",
          type: "boolean",
          default: "true",
          en: "Hairlines between content columns.",
          ru: "Тонкие линии между колонками.",
        },
        {
          name: "striped",
          type: "boolean",
          default: "false",
          en: "Every second row one opaque step off the table fill.",
          ru: "Каждая вторая строка на шаг темнее заливки таблицы.",
        },
        {
          name: "highlightRowOnHover",
          type: "boolean",
          default: "true",
          en: "Row wash on hover (and a pressed wash on clickable rows).",
          ru: "Подсветка строки при наведении (и нажатия у кликабельных строк).",
        },
        {
          name: "highlightColumnOnHover",
          type: "boolean",
          default: "false",
          en: "Column wash under the pointer (head and cells).",
          ru: "Подсветка колонки под курсором (шапка и ячейки).",
        },
        {
          name: "onRowClick",
          type: "(row: Row, index: number, event: MouseEvent<HTMLTableRowElement>) => void",
          en: "Row click; rows get a pointer cursor.",
          ru: "Клик по строке; у строк появляется курсор-указатель.",
        },
        {
          name: "labels",
          type: "Partial<DataTableLabels>",
          en: "Built-in strings, see Labels.",
          ru: "Системные строки, см. «Доступность».",
        },
        {
          name: "…rest",
          type: 'Omit<HTMLAttributes<HTMLDivElement>, "children">',
          en: "`className` and the other attributes of the root `<div>`.",
          ru: "`className` и остальные атрибуты корневого `<div>`.",
        },
      ],
    },
    {
      name: "DataTableColumn<Row>",
      en: "One column of `columns`: data, not a part.",
      ru: "Одна колонка из `columns`: данные, а не часть разметки.",
      props: [
        {
          name: "id",
          type: "string",
          required: true,
          en: "Unique column id (sort state, `data-column-id`).",
          ru: "Уникальный id колонки (сортировка, `data-column-id`).",
        },
        {
          name: "header",
          type: "ReactNode",
          required: true,
          en: "Head content.",
          ru: "Содержимое заголовка.",
        },
        {
          name: "accessor",
          type: "keyof Row | ((row: Row) => unknown)",
          en: "Cell value (rendered as text, `—` for empty) and the default sort value.",
          ru: "Значение ячейки (выводится текстом, `—` для пустого) и значение для сортировки.",
        },
        {
          name: "cell",
          type: "(row: Row) => ReactNode",
          en: "Custom cell content.",
          ru: "Своё содержимое ячейки.",
        },
        {
          name: "sortable",
          type: "boolean",
          en: "The head becomes a sort button with `aria-sort`.",
          ru: "Заголовок становится кнопкой сортировки с `aria-sort`.",
        },
        {
          name: "sortAccessor",
          type: "(row: Row) => unknown",
          en: "Value to sort by instead of `accessor`.",
          ru: "Значение для сортировки вместо `accessor`.",
        },
        {
          name: "sortComparator",
          type: "(a: Row, b: Row, order: DataTableOrder) => number",
          en: "Custom comparison.",
          ru: "Своё сравнение строк.",
        },
        {
          name: "align",
          type: '"start" | "center" | "end"',
          default: '"start" ("end" with numeric)',
          en: "Cell alignment; heads do not follow it.",
          ru: "Выравнивание ячеек; заголовки за ним не следуют.",
        },
        {
          name: "headerAlign",
          type: '"start" | "center" | "end"',
          default: '"start"',
          en: "Head alignment; the sort icon stays at the end edge.",
          ru: "Выравнивание заголовка; иконка сортировки всегда у конца ячейки.",
        },
        {
          name: "numeric",
          type: "boolean",
          en: "Tabular figures, no wrapping, end alignment unless `align` is set.",
          ru: "Табличные цифры, без переноса, выравнивание по концу, если не задан `align`.",
        },
        {
          name: "truncate",
          type: "boolean",
          en: "One line with an ellipsis; width from `maxWidth` (or `width`); string values get a `title`.",
          ru: "Одна строка с многоточием; ширина из `maxWidth` (или `width`); строковые значения получают `title`.",
        },
        {
          name: "grow",
          type: "boolean",
          en: "Takes the free width and wraps its text; the table then fills its container. With `minWidth` it never gets narrower: below that the table scrolls instead of cells overlapping.",
          ru: "Забирает свободную ширину и переносит текст; таблица тогда заполняет контейнер. С `minWidth` не становится уже: ниже этого таблица прокручивается, ячейки не наезжают.",
        },
        {
          name: "hideable",
          type: "boolean",
          default: "true",
          en: "The column can be hidden through `hiddenColumns`; `false` for the key column that names the row.",
          ru: "Колонку можно скрыть через `hiddenColumns`; `false` — для ключевой колонки, которая называет строку.",
        },
        {
          name: "width · minWidth · maxWidth",
          type: "string",
          en: 'CSS sizes of the column (`"14rem"`).',
          ru: 'CSS-размеры колонки (`"14rem"`).',
        },
      ],
    },
  ],
  labels: [
    {
      key: "loading",
      default: "Загрузка данных…",
      en: "Screen-reader status while skeleton rows are shown.",
      ru: "Статус для скринридера, пока видны скелетоны.",
    },
    {
      key: "empty",
      default: "Нет данных для отображения.",
      en: "Default empty-state text.",
      ru: "Текст пустого состояния по умолчанию.",
    },
    {
      key: "range",
      default: "Показано {from}–{to} из {total}",
      en: "Footer range line; `{from}`, `{to}`, `{total}` are replaced.",
      ru: "Строка диапазона в подвале; `{from}`, `{to}`, `{total}` заменяются.",
    },
    {
      key: "loadingMore",
      default: "Догружаем строки…",
      en: "Footer status while `loadingMore`.",
      ru: "Статус в подвале при `loadingMore`.",
    },
    {
      key: "scrollForMore",
      default: "Прокрутите вниз для загрузки",
      en: "Footer hint when more rows can appear by scrolling.",
      ru: "Подсказка в подвале, когда прокрутка добавит строки.",
    },
    {
      key: "selectAll",
      default: "Выбрать все строки",
      en: "Name of the head «select all» checkbox.",
      ru: "Имя флажка «выбрать все» в шапке.",
    },
    {
      key: "selectRow",
      default: "Выбрать строку {label}",
      en: "Name of a row checkbox; `{label}` is `getRowLabel(row)`, empty without it.",
      ru: "Имя флажка строки; `{label}` — `getRowLabel(row)`, без него пусто.",
    },
    {
      key: "selectedCount",
      default: "Выбрано: {count}",
      en: "Polite announcement after the selection changes.",
      ru: "Вежливое объявление после смены выбора.",
    },
    {
      key: "expand",
      default: "Развернуть строку {label}",
      en: "Name of the toggle of a collapsed row.",
      ru: "Имя переключателя свёрнутой строки.",
    },
    {
      key: "collapse",
      default: "Свернуть строку {label}",
      en: "Name of the toggle of an expanded row.",
      ru: "Имя переключателя раскрытой строки.",
    },
  ],
};
