import type { ComponentApi } from "../../../scripts/docs/componentApi";

export const api: ComponentApi = {
  parts: [
    {
      name: "Slider",
      en: '`ref` → `HTMLDivElement` (the field frame). A framed field like every other: the label row with the value, a native `<input type="range">` (transparent, on top) over the visual track, fill and thumb, then the hint or the error. Field-root rule: `className`, `ref` and the rest go to the frame; `id` and `aria-label` to the range input.',
      ru: 'Поле в рамке, как остальные: подпись со значением, нативный `<input type="range">` поверх дорожки, заливки и ползунка, под ним подсказка или ошибка.',
      props: [
        {
          name: "value",
          type: "number",
          en: "Controlled value; clamped to `min`…`max`.",
          ru: "Управляемое значение; ограничивается `min`…`max`.",
        },
        {
          name: "defaultValue",
          type: "number",
          default: "min",
          en: "Initial value when uncontrolled.",
          ru: "Начальное значение без контроля.",
        },
        {
          name: "onValueChange",
          type: "(value: number) => void",
          en: "Called with the new number while dragging and on every key step.",
          ru: "Новое число при перетаскивании и каждом шаге с клавиатуры.",
        },
        {
          name: "min",
          type: "number",
          default: "0",
          en: "Lower bound.",
          ru: "Нижняя граница.",
        },
        {
          name: "max",
          type: "number",
          default: "100",
          en: "Upper bound.",
          ru: "Верхняя граница.",
        },
        {
          name: "step",
          type: "number",
          default: "1",
          en: "Step of the keyboard and of the snapping; fractions allowed.",
          ru: "Шаг клавиатуры и привязки; можно дробный.",
        },
        {
          name: "size",
          type: '"xs" | "s" | "m" | "l" | "xl"',
          default: 'host tier, else "m"',
          en: "Tier of the track thickness T (thumb 4.5T × 3T), the label, the value and the hint. Without it the tier of its host (a form, a panel), else `m`.",
          ru: "Ярус толщины дорожки T (ползунок 4.5T × 3T), подписи и значения.",
        },
        {
          name: "tone",
          type: '"neutral" | "accent" | "success" | "warning" | "danger" | "info"',
          default: '"accent"',
          en: "Color of the filled part of the track.",
          ru: "Цвет заполненной части дорожки.",
        },
        {
          name: "disabled",
          type: "boolean",
          en: "Muted track and thumb, dimmed label and value, no interaction.",
          ru: "Приглушённые дорожка, ползунок, подпись и значение; без взаимодействия.",
        },
        {
          name: "label",
          type: "ReactNode",
          en: "Visible label linked to the range input (`<label htmlFor>`). Without it, set `aria-label`.",
          ru: "Видимая подпись, связанная с input. Без неё задайте `aria-label`.",
        },
        {
          name: "required",
          type: "boolean",
          en: "Red `*` after the label (`aria-hidden`); a range always has a value, so there is no native `required`.",
          ru: "Красная `*` после подписи; у ползунка всегда есть значение, нативного `required` нет.",
        },
        {
          name: "optional",
          type: "boolean",
          en: "Muted marker right after the label text (`labels.optional`).",
          ru: "Приглушённая пометка после подписи (`labels.optional`).",
        },
        {
          name: "hint",
          type: "ReactNode",
          en: "Help text under the track (`aria-describedby`). Hidden while `error` is shown.",
          ru: "Подсказка под дорожкой; скрывается, пока показан `error`.",
        },
        {
          name: "error",
          type: "ReactNode",
          en: "Error message in the hint slot; implies `invalid`.",
          ru: "Текст ошибки на месте подсказки; включает `invalid`.",
        },
        {
          name: "invalid",
          type: "boolean",
          en: "`aria-invalid` on the range input and a danger focus ring on the thumb. A non-empty `error` implies it.",
          ru: "`aria-invalid` на input и красное кольцо фокуса у ползунка.",
        },
        {
          name: "showValue",
          type: "boolean",
          default: "false",
          en: "Shows the current value at the end of the label row (tabular numbers, `aria-hidden` — the input announces it).",
          ru: "Текущее значение в конце строки подписи (табличные цифры).",
        },
        {
          name: "formatValue",
          type: "(value: number) => string",
          en: "Formats the shown value and `aria-valuetext` (units, currency).",
          ru: "Формат показанного значения и `aria-valuetext` (единицы, валюта).",
        },
        {
          name: "id",
          type: "string",
          en: "Id of the range input (generated when omitted); hint id is `<id>-hint`, error id is `<id>-error`.",
          ru: "Id input; иначе генерируется.",
        },
        {
          name: "aria-label",
          type: "string",
          en: "Accessible name when there is no visible `label`.",
          ru: "Доступное имя, когда нет видимой подписи.",
        },
        {
          name: "aria-describedby",
          type: "string",
          en: "Merged before the hint / error ids on the range input.",
          ru: "Добавляется перед id подсказки и ошибки.",
        },
        {
          name: "labels",
          type: "Partial<SliderLabels>",
          en: "Built-in strings, see Labels.",
          ru: "Системные строки, см. «Доступность».",
        },
        {
          name: "…rest",
          type: 'Omit<HTMLAttributes<HTMLDivElement>, "id" | "children" | "defaultValue" | "defaultChecked" | "onChange">',
          en: "`className`, `style` and the other attributes of the field frame `<div>`.",
          ru: "`className`, `style` и остальные атрибуты `<div>` рамки поля.",
        },
      ],
    },
  ],
  labels: [
    {
      key: "optional",
      default: "необязательно",
      en: "Marker after the label when `optional`.",
      ru: "Пометка после подписи при `optional`.",
    },
  ],
};
